---
version: '3.9'

# https://docs.docker.com/compose/compose-file/#using-extensions-as-fragments
x-common-config: &common-config
  restart: always
  image: base_nodejs
  build:
    context: .
    dockerfile: dev.Dockerfile
  volumes:
    - .:/app

services:
  postgres:
    image: postgres:13-alpine
    profiles: [services, all]
    container_name: zachgoll-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpw
      POSTGRES_DB: personal_local
    volumes:
      - postgres_personal_data:/var/lib/postgresql/data

  site:
    <<: *common-config
    profiles: [site, all]
    env_file: apps/personal-site/.env.local
    container_name: zachgoll-site
    ports:
      - '4200:4200'

  design-system:
    <<: *common-config
    profiles: [design-system, all]
    env_file: .env
    container_name: zachgoll-design-system
    logging:
      driver: none
    ports:
      - '4400:4400'

volumes:
  postgres_personal_data:
